src/crossmarket/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url

from satchmo_store.urls import urlpatterns
from satchmo_utils import urlhelper

from apps.events.views import event_details, event_attendees, event_hostessportal, event_attendee_status


urlpatterns += patterns('',
     (r'^accounts/', include('apps.account.urls')),
     #(r'^manage/messages/', include('apps.messages.urls')),
     (r'^manage/tools/support/', include('apps.support.urls')),
     (r'^manage/', include('apps.manage.urls')),
     (r'^one-page-checkout/', include('apps.one_page_checkout.urls')),
     (r'^backend/dashboard/', include('apps.dashboard.urls')),
     (r'^tinymce/', include('tinymce.urls')),
     (r'^dashboard/$', 'apps.home.views.dashboard', {}),
     (r'^accounts/login/$', 'django.contrib.auth.views.login', {}),
     (r'^accounts/login/$', 'django.contrib.auth.views.login', {}),
     (r'^', include('apps.home.urls'), {}),
)

urlpatterns += patterns('',
    url(r'^parties/(?P<code>[\{\}\w-]+)/$', event_details, name="events_detail"),
    url(r'^parties/(?P<code>[\{\}\w-]+)/invite/$', event_attendees, name="events_attendees"),
    url(r'^parties/(?P<code>[\{\}\w-]+)/hostessportal/$', event_hostessportal, name="events_hostessportal"),
    url(r'^parties/(?P<code>[\{\}\w-]+)/attend/(?P<attendee_code>[\w]+)/$', event_attendee_status, name="events_attendee_status"),
    # url(r'^parties/(?P<code>[\{\}\w-]+)/attend/(?P<attendee_code>[\w]+)/(?P<status>yes|no|maybe|pending)$', event_attendee_status, name="events_attendee_status_auto"),
)

# This can be removed. Only used to test SOAP API
urlpatterns += patterns('',
    url(r'^testing_soap/', include("apps.api_wrapper.urls"), name="testing_soap"),
)

urlhelper.replace_urlpatterns(
    urlpatterns, [
        url(r'^(?P<parent_slugs>([-\w]+/)*)?(?P<slug>[-\w]+)/$', 'apps.dashboard.views.category_view', {}, name='satchmo_category'),
        url(r'^cart/$', 'apps.dashboard.views.cart_display', {}, 'satchmo_cart'),
    ]
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':  settings.MEDIA_ROOT, 'show_indexes': True}),
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root':  settings.STATIC_ROOT, 'show_indexes': True}),
        (r'^static-admin/(?P<path>.*)$', 'django.views.static.serve', {'document_root':  settings.ADMIN_MEDIA_ROOT, 'show_indexes': True}),
    )

src/crossmarket/apps/events/models.py
import datetime
import uuid

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, Q
from django.db.models.signals import post_save
from django.contrib.localflavor.us.models import (PhoneNumberField,
    USPostalCodeField, USStateField)
from django.core.mail import EmailMessage
from django.template.loader import render_to_string

from satchmo_store.shop.models import Order
from product.models import Product


ATTEND = (
    (1, 'Yes'),
    (2, 'No'),
    (3, 'Maybe'),
    (4, 'Pending'),
)

STATUS = (
    (1, "Requested"),
    (2, "Scheduled"),
    (3, "Open"),
    (4, "Closed"),
    (5, "Canceled"),
)


def code_maker(model=None, length=6, key_name='code'):
    """Random code generator."""
    params = {key_name: None}
    while True:
        key = uuid.uuid4().hex[:length]
        params[key_name] = key

        try:
            has_key = model.objects.get(**params)
        except model.DoesNotExist:
            break

    return key


class EventManager(object):
    def past_events(self):
        now = datetime.datetime.now()
        delta = datetime.timedelta(hours=1)
        return self.filter(start__lte=now-delta).order_by('-starts_at')
        
    def future_events(self):
        now = datetime.datetime.now()
        delta = datetime.timedelta(hours=1)
        return self.filter(start__gte=now-delta).order_by('-starts_at')
    
class Event(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    description = models.TextField()
    code = models.SlugField(max_length=50, editable=False, unique=True, default=lambda: code_maker(Event))
    starts_at = models.DateTimeField(verbose_name="Party Date")
    
    street = models.CharField(max_length=100)
    street2 = models.CharField(max_length=100, blank=True, null=True) 
    city = models.CharField(max_length=75)
    state = USStateField()
    postal_code = models.CharField("Zip/Postal", max_length=12)

    use_personal_website = models.BooleanField(default=False)
    use_evite = models.BooleanField(default=False)

    photo = models.ForeignKey("EventPhoto")

    is_closed = models.BooleanField(default=False)
    closed_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now)
    status = models.IntegerField(choices=STATUS, default=1)
    
    #ALTER TABLE `events_event` ADD COLUMN `redeemed_hostess_reward` TINYINT(1)  NULL DEFAULT false;
    redeemed_hostess_reward = models.BooleanField(default=False)


    objects = EventManager()


    def attendee_cart(self):
        return EventAttendeeCart.objects.filter(event=self, active=True)

    def can_order(self):
        if self.status==3 and self.starts_at>(datetime.datetime.today()):
            return True
        return False
    
    def is_future(self):
        return self.starts_at >= datetime.datetime.now()

    def __unicode__(self):
        return "%s, %s" % (self.code, self.starts_at.date())

    class Meta:
        ordering = ('starts_at', 'name',)

    def attendee(self):
        return Attendee.objects.filter(event=self)

    def host(self):
        return Host.objects.get(event=self)

    def orders(self):
        from apps.compensation.models import PartyOrder
        orders=[]
        pos=PartyOrder.objects.filter(party=self)
        for po in pos:
            orders.append(po.order)
        return orders

    def orders_total(self):
        from apps.compensation.models import PartyOrder
        st=PartyOrder.objects.filter(party=self).aggregate(total=Sum('order__sub_total'))
        st=(st['total'] if st['total'] is not None else 0.00 )
        dt=PartyOrder.objects.filter(party=self).aggregate(total=Sum('order__discount'))
        dt=( dt['total'] if dt['total'] is not None else 0.00 )
        return st-dt

    def hostess_rewards(self):
        from apps.compensation.models import HostingReward
        total=self.orders_total()
        hr=HostingReward.objects.filter((Q(min_sale__lte=total)&Q(max_sale=0.00)) | Q(min_sale__lte=total)&Q(max_sale__gt=total) ).order_by('min_sale')
        if len(hr)>0:
            return hr[0]
        return False

class EventPhoto(models.Model):
    name = models.CharField(max_length=25)
    photo = models.ImageField(upload_to="events/photos/")
    is_enabled = models.BooleanField(default=True)
    
    def image_tag(self):
        return '<img src="%s" width="" height="" alt="">' % self.photo.url
    
    def __unicode__(self):
        return "%s" % (self.name)


class Host(models.Model):
    event = models.OneToOneField(Event)
    user = models.ForeignKey(User, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    street2 = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=75)
    state = USStateField()
    postal_code = models.CharField("Zip/Postal", max_length=12)

    phone = PhoneNumberField()
    email = models.EmailField()

    has_accepted = models.BooleanField(default=False)

    def name(self):
        return "%s %s"%(self.first_name, self.last_name)


class HostReward(models.Model):
    host = models.ForeignKey(Host)
    order = models.ForeignKey(Order)
    personal_sales = models.DecimalField(max_digits=9, decimal_places=2)
    reward_credit = models.DecimalField(max_digits=9, decimal_places=2)
    enroll_credit = models.DecimalField(max_digits=9, decimal_places=2)
    enroll_credit_redeemed = models.BooleanField()
    is_half_off = models.BooleanField()


class ShipTo(models.Model):
    event = models.OneToOneField(Event)
    user = models.ForeignKey(User, blank=True, null=True)
    
    name = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    street2 = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=75)
    state = USStateField()
    postal_code = models.CharField("Zip/Postal", max_length=12)

    phone = PhoneNumberField()
    email = models.EmailField()

    has_shipped = models.BooleanField(default=False)

#drop events_attendee events_event events_eventattendeecart events_eventattendeecartdetail events_host
#then syncdb
#and then import parties
class Attendee(models.Model):
    event = models.ForeignKey(Event)
    code = models.SlugField(max_length=25, editable=False, unique=True,
        default=lambda: code_maker(Attendee))
    user = models.ForeignKey(User, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    email = models.CharField(max_length=100)
    phone = PhoneNumberField(blank=True, null=True)
    
    street = models.CharField(max_length=100, blank=True, null=True)
    street2 = models.CharField(max_length=100, blank=True, null=True) 
    city = models.CharField(max_length=100, blank=True, null=True)
    state = USStateField(blank=True, null=True)
    postal_code = models.CharField("Zip/Postal", max_length=12,
        blank=True, null=True)

    birthday = models.DateField(blank=True, null=True)
    
    status = models.IntegerField(default=4, choices=ATTEND)

    def name(self):
        return "%s %s"%(self.first_name, self.last_name)

# Signal for emailing a newly added attendee.
def email_event_attendee(sender, **kwargs):
    instance = kwargs.get("instance", None)
    created = kwargs.get("created", False)

    if created:
        html = render_to_string('events/email_invite.html', {
            'event': instance.event, 'code': instance.code,
            'STATIC_URL': settings.STATIC_URL, "is_email":True})
        subject = 'Party invite: %s' % instance.event.name
        msg = EmailMessage(subject, html, settings.DEFAULT_FROM_EMAIL, [instance.email])
        msg.content_subtype = "html"  # Main content is now text/html
        msg.send()

post_save.connect(email_event_attendee, sender=Attendee)


class EventAttendeeCart(models.Model):
    event=models.ForeignKey(Event)
    attendee=models.ForeignKey(Attendee)
    direct_ship=models.BooleanField(default=False)
    active=models.BooleanField(default=False)
    def details(self):
        return EventAttendeeCartDetail.objects.filter(attendee_cart=self)
    
class EventAttendeeCartDetail(models.Model):
    attendee_cart=models.ForeignKey(EventAttendeeCart)
    product=models.ForeignKey(Product)
    quantity=models.IntegerField(default=0)

src/crossmarket/apps/geo/models.py
from django.db import models
#from django.contrib.gis.db import models

class ZipCode(models.Model):
    zip_code=models.CharField(unique=True, blank=False, null=False, max_length=5)
    city=models.CharField(max_length=128)
    state_code=models.CharField(max_length=2)
    state=models.CharField(max_length=128)
    latitude=models.FloatField()
    longitude=models.FloatField()
    #objects=models.GeoManager()kk

src/crossmarket/apps/events/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from django.forms.formsets import formset_factory
from django.conf import settings
from apps.events.models import Event, Host, ShipTo, Attendee, EventPhoto, ATTEND


class AttendeeStatusForm(forms.Form):
    attend = forms.ChoiceField(choices=ATTEND, help_text="Are you attending?")


class EventPhotoForm(ModelForm):
    class Meta:
        model = EventPhoto
        exclude = ('name', 'photo')


class EventForm(ModelForm):
    starts_at=forms.DateTimeField(widget=forms.DateTimeInput(format=settings.DATE_INPUT_FORMATS[0]), input_formats=settings.DATE_INPUT_FORMATS)
    def clean_starts_at(self):
        starts_at = self.cleaned_data['starts_at']

        now = datetime.datetime.now()
        if now > starts_at:
            raise forms.ValidationError("Please select a date.")
        return starts_at

    class Meta:
        model = Event
        exclude = ('owner', 'is_closed', 'created_at', 'closed_at', 'redeemed_hostess_reward')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['state'].widget.attrs['class'] = 'exclude'
        self.fields['photo'].widget.attrs['class'] = 'exclude'
        self.fields['status'].choices=[(1, 'Requested'), (2, 'Scheduled'), (3, 'Open'), (5, 'Canceled')]

class HostForm(ModelForm):

    class Meta:
        model = Host
        exclude = ('event', 'user', 'has_accepted')

class ShipToForm(ModelForm):

    class Meta:
        model = ShipTo
        exclude = ('event', 'has_shipped', 'user')

class AttendeeForm(ModelForm):
    #exclude
    class Meta:
        model = Attendee
        exclude = ('event', 'user', 'is_attending', 'birthday')

    def __init__(self, *args, **kwargs):
        super(AttendeeForm, self).__init__(*args, **kwargs)
        self.fields['status'].widget.attrs['class'] = 'exclude'
        self.fields['state'].widget.attrs['class'] = 'exclude'

    def clean_street(self):
        if 'first_name' in self.cleaned_data:
            if self.cleaned_data['first_name']==self.cleaned_data['street']:
                raise forms.ValidationError("Cannot be same as first name.")
        return self.cleaned_data['street']

AttendeeFormSet = formset_factory(AttendeeForm, extra=2)

src/crossmarket/templates/events/_details.html
{% load i18n %}

{% block header-text %}
<div>
{% ifequal request.GET.status '1' %}
<div class="box-blue">
  <h2><strong>Thanks!</strong></h2>
  <p style="color:#CE248C;"><a href="/{{ event.pk }}" style="font-weight:normal;">Thanks for joining in the party, <span style="text-decoration:underline;">Click here </span> if you want to purchase some nails for the party?</a></p>
</div>
{% else %}
  {% ifequal request.GET.status '2' %}
    <div class="box-blue">
      <h2><strong>Sorry!</strong></h2>
      <p style="color:#CE248C;">We hope to see you in the next party.</p>
    </div>
  {% endifequal %}
{% endifequal %}
</div>
{% endblock %}


<div id="main_content">
    <div style="clear:both"></div>
    <img src="{% if is_email %}http://{{ event.owner.website.domain }}{% endif %}{{ event.photo.photo.url }}" {% if not is_admin %}width="550px"{% endif %} alt="">

    <div style="float:right;width:350px;margin-top:10px">
        <h2 style="border:0px !important">{{ event.name }}</h2>

        <div>{{ event.description|linebreaks }}</div>
        <h2 style="border:none !important">When</h2>

        <div style="margin-top:15px; margin-bottom:15px">{{ event.starts_at }}</div>
        <h2 style="border:0px !important">Where</h2>

        <div style="line-height:1.7em">{{ event.street }}</div>
        <div style="line-height:1.7em">{{ event.street2 }}</div>
        <div>{{ event.city }}, {{ event.state }} {{ event.postal_code }}</div>
        <div style="margin-top:20px; margin-bottom:20px">
          {% if is_attendee_status %}
	    {% if not request.GET.status %} 
              <form action="." method="post" accept-charset="utf-8" style="width:150px;">
                {% csrf_token %}
                {{ form }}
                <p><input class="add" type="submit" value="Submit"></p>
              </form>
	    {% endif %}
          {% else %}
            {% if is_email %}
              <a href="http://{{ event.owner.website.domain }}{% url events_attendee_status event.code code %}" class="add">{% trans "View on website" %}</a> | 
              <a href="http://{{ event.owner.website.domain }}{% url events_attendee_status event.code code %}?attend=1" class="add">{% trans "Attend" %}</a> | 
              <a href="http://{{ event.owner.website.domain }}{% url events_attendee_status event.code code %}?attend=2" class="add">{% trans "I am not able to attend" %}</a>
            {% else %}
              <a href="http://{{ event.owner.website.domain }}{% if is_admin %}{% url events_manager_attendees event.code %}{% else %}{% url events_attendees event.code %}{% endif %}" class="add" style="width:40%; float:left;">{% if is_admin %}{% trans "Invite Guests" %}{% else %}{% trans "Attend?" %}{% endif %}</a>
              {% if event.can_order %}<a href="{% if user.is_authenticated %}{% url manager_set_wholesale_discount %}?slug=Party&party={{ event.pk }}{% else %}{% url set_party_purchase %}?party={{ event.pk }}{% endif %}" class="add" style="width:40%; float:right;">Order</a> {% endif %}
          {% endif %}
          {% endif %}
        </div>
    </div>
    <div style="clear:both;"></div>
</div>

src/crossmarket/templates/events/attendees_list.html
{% extends "manage/base.html" %}
{% load i18n %}
{% block title %}{% trans "Party Manager" %}{% endblock %}

{% block extra-css %}
    <script defer src="{{ STATIC_URL }}manage/js/mylibs/jquery.dataTables.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sprite.tables.css">

    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sidebar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/plugin.calendar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sprite.forms.css">
    <style type="text/css" media="screen">
        .table-events {
            width: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="main_content">
        <h2 class="grid_12">{{ event.name }}</h2>

        <div style="clear:both"></div>
        <div class="box">
            <div class="header no-icon">
                <h3>{% trans "Attendees" %}</h3>
                <span id="bill-info"></span>
            </div>
            <div class="content no-padding">
                <table class="table table-events">
                    <thead>
                    <tr>
                        <th>{% trans "Attendee" %}</th>
                        <th>{% trans "Email" %}</th>
                        <th>{% trans "Phone" %}</th>
                        <th>{% trans "Status" %}</th>
                        <th>{% trans "Actions" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for a in event.attendee_set.all %}
                    <tr style="text-align:center;">
                            <td><a href="{% url events_attendee_edit code=event.code attendee_id=a.pk %}">{{ a.name }}</a></td>
                            <td>{{ a.email }}</td>
                            <td>{{ a.phone }}</td>
                            <td>{{ a.get_status_display }}</td>
                            <td><button class="button remove-guest" href="{% url events_attendee_list code=event.code %}" attendee_id="{{ a.pk }}">Remove</button></td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td colspan="4" style="text-align:center;padding:5px 0px">{% trans "No one has been invited yet" %}</td>
                    </tr>
                    {% endfor %}
                    <tbody>
                </table>
            </div>
        </div>

        <div style="float:right;width:100px;margin-top:10px; margin-bottom:50px">
            <a class="add"
               href="{% url events_manager_attendees event.code %}?next={% url events_attendee_list event.code %}">{% trans "Invite Guest?" %}</a>
        </div>
        <div style="clear:both"></div>
    </div>
    
{% endblock %}

{% block extra-js %}
<script>
    $(document).ready(function(){
        $(".remove-guest").click(function(e){
            url = $(e.currentTarget).attr("href");
            resource_id = $(e.currentTarget).attr("attendee_id");
            if(confirm("{% trans 'Are you sure you want to remove this guest from your party?' %}")){
                $.get(
                    url,
                    {"resource_id": resource_id},
                    function(data){
                        if (data.status === "Success"){
                            // Remove element from the DOM
                            $(e.currentTarget).parent().parent().remove()

                            // Display message
                            alert(data.message);
                        }
                    }, "json"
                );
            }
        });
    });
</script>
{% endblock %}

src/crossmarket/templates/events/cancel.html
{% extends "manage/base.html" %}
{% block title %}Cancel Party{% endblock %}


{% block content %}
    <div id="main_content">
        <h2 class="grid_12">Cancel Party</h2>

        <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sidebar.css">
        <script defer src="{{ STATIC_URL }}manage/js/mylibs/jquery.validate.js"></script>
        <script defer src="{{ STATIC_URL }}manage/js/mylibs/jquery.checkbox.js"></script>
        <script defer src="{{ STATIC_URL }}manage/js/mylibs/jquery.chosen.js"></script>
        <script defer src="{{ STATIC_URL }}manage/js/mylibs/jquery.placeholder.js"></script>
        <script defer src="{{ STATIC_URL }}manage/js/mylibs/jquery.miniColors.js"></script>
        <script defer src="{{ STATIC_URL }}manage/js/mylibs/fullcalendar.js"></script>
        <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/plugin.calendar.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sprite.forms.css">

        {% for field in form %}
            <div class="form-field">{{ field.labels_tag }} {{ field }}</div>
        {% endfor %}

{% endblock %}

src/crossmarket/templates/events/event_step2.html
{% extends "manage/base.html" %}
{% load i18n %}
{% block title %}{% trans "Party Manager" %}{% endblock %}

{% block extra-css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sidebar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/plugin.calendar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sprite.forms.css">
    <style type="text/css" media="screen">
        .table-events {
            width: 100%;
        }
    </style>
{% endblock %}

{% block extra-js %}

    <script type="text/javascript" charset="utf-8">
        var JAMBERRY = {};
        JAMBERRY.parties = {
            'name':"{{ consultant.name }}",
            'street':'{{ consultant.street }}',
            'street2':'{{ consultant.street2 }}',
            'city':'{{ consultant.city }}',
            'state':'{{ consultant.state }}',
            'postal_code':'{{ consultant.postal_code }}',
            'phone':'{{ consultant.phone }}',
            'email':'{{ consultant.email }}'
        }

        $('#id_is_host').click(function () {
            if (this.checked == true) {
                $('#id_name').val(JAMBERRY.parties.name);
                $('#id_street').val(JAMBERRY.parties.street);
                $('#id_street2').val(JAMBERRY.parties.street2);
                $('#id_city').val(JAMBERRY.parties.city);
                $('#id_state').val(JAMBERRY.parties.state);
                $('#id_postal_code').val(JAMBERRY.parties.postal_code);
                $('#id_phone').val(JAMBERRY.parties.phone);
                $('#id_email').val(JAMBERRY.parties.email);
            } else {
                $('#form-step3')[0].reset();
            }
        });

    </script>

{% endblock %}

{% block content %}
    <div id="main_content">
        <form action="" id="form-step2" method="post" enctype="multipart/form-data" style="width:50% !important">
            {% csrf_token %}
            <div class="box closed">
                <div class="header no-icon">
                    <h3>{% trans "Host Info" %}</h3>
                </div>
                <fieldset class="module aligned">
                    <table class="left_align form_fields" style="margin:0px;" cellspacing="0" border="0"
                           cellpadding="0">
                        <tbody>
                        <tr class="">
                            <td><label for="id_is_host">Is host</label></td>
                            <td><input type="checkbox" name="is_host" id="id_is_host">

                                <div>Consultant is the host</div>
                            </td>
                        </tr>
                        {% for item in form %}
                            <tr class="">
                                <td>{{ item.label_tag }}</td>
                                <td>{{ item }} {% if item.help_text %}
                                    <div>{{ item.help_text }}</div>{% endif %}{{ item.errors }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </fieldset>
                <div class="form-field" style="margin:30px 0px">
                    <input type="submit" class="add" name="id_submit" value="Continue" id="submit">
                </div>
        </form>
    </div>
    <div style="clear:both"></div>
    </div>
{% endblock %}

src/crossmarket/templates/events/event_step3.html
{% extends "manage/base.html" %}
{% load i18n %}
{% block title %}{% trans "Party Manager" %}{% endblock %}

{% block extra-css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sidebar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/plugin.calendar.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}manage/css/sprite.forms.css">
    <style type="text/css" media="screen">
        .table-events {
            width: 100%;
        }
    </style>
{% endblock %}

{% block extra-js %}

    <script type="text/javascript" charset="utf-8">
        var JAMBERRY = {};
        JAMBERRY.parties = {
            'name':"{{ consultant.name }}",
            'street':'{{ consultant.street }}',
            'street2':'{{ consultant.street2 }}',
            'city':'{{ consultant.city }}',
            'state':'{{ consultant.state }}',
            'postal_code':'{{ consultant.postal_code }}',
            'phone':'{{ consultant.phone }}',
            'email':'{{ consultant.email }}'
        }

        $('#id_ship_to_consultant').click(function () {
            if (this.checked == true) {
                $('#id_name').val(JAMBERRY.parties.name);
                $('#id_street').val(JAMBERRY.parties.street);
                $('#id_street2').val(JAMBERRY.parties.street2);
                $('#id_city').val(JAMBERRY.parties.city);
                $('#id_state').val(JAMBERRY.parties.state);
                $('#id_postal_code').val(JAMBERRY.parties.postal_code);
                $('#id_phone').val(JAMBERRY.parties.phone);
                $('#id_email').val(JAMBERRY.parties.email);
            } else {
                $('#form-step3')[0].reset();
            }
        });

    </script>

{% endblock %}

{% block content %}
    <div id="main_content">
        <form action="" id="form-step3" method="post" enctype="multipart/form-data" style="width:50% !important">
            {% csrf_token %}
            <div class="box closed">
                <div class="header no-icon">
                    <h3>{% trans "Ship to Info" %}</h3>
                </div>
                <fieldset class="module aligned">
                    <table class="left_align form_fields" style="margin:0px;" cellspacing="0" border="0"
                           cellpadding="0">
                        <tbody>
                        <tr class="">
                            <td><label for="id_ship_to_consultant">Ship to consultant</label></td>
                            <td><input type="checkbox" name="ship_to_consultant" id="id_ship_to_consultant"></td>
                        </tr>
                        {% for item in form %}
                            <tr class="">
                                <td>{{ item.label_tag }}</td>
                                <td>{{ item }} {% if item.help_text %}
                                    <div>{{ item.help_text }}</div>{% endif %}{{ item.errors }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </fieldset>
                <div class="form-field" style="margin:30px 0px">
                    <input type="submit" class="add" name="id_submit" value="Finish" id="submit">
                </div>
        </form>
    </div>
    <div style="clear:both"></div>
    </div>
{% endblock %}